### ISSUE TITLE
have a command line option that will delete the tb replication slot

### ISSUE THREAD

**Issue by rjnn** [MaterializeInc/tb#17]
Ctrl+Cing `tb` and restarting it failed because

```
org.apache.kafka.connect.errors.ConnectException: org.postgresql.util.PSQLException: ERROR: replication slot "tb" already exists
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:116)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:104)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:722)
	at io.materialize.Binlogger.main(Binlogger.java:137)
Caused by: org.postgresql.util.PSQLException: ERROR: replication slot "tb" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:309)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:272)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:267)
	at io.debezium.connector.postgresql.connection.PostgresReplicationConnection.createReplicationSlot(PostgresReplicationConnection.java:293)
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:113)
	... 3 more
Exception in thread "main" java.lang.NullPointerException
	at io.materialize.Binlogger.main(Binlogger.java:139)
```

I had to `psql` in and manually run

```
arjun=# select pg_drop_replication_slot('tb');
 pg_drop_replication_slot 
--------------------------
 
(1 row)
```

This should not be necessary

**Comment by quodlibetor** [comment]
This is currently supported via the `--replication-slot` flag.
